/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        brand: {
          50: "#eef2ff",
          100: "#e0e7ff",
          200: "#c7d2fe",
          300: "#a5b4fc",
          400: "#818cf8",
          500: "#6366f1",
          600: "#4f46e5",
          700: "#4338ca",
          800: "#3730a3",
          900: "#312e81",
          950: "#1e1b4b",
        },
        th: {
          page: "var(--th-page)",
          panel: "var(--th-panel)",
          "panel-alt": "var(--th-panel-alt)",
          hover: "var(--th-hover)",
          subtle: "var(--th-subtle)",
          muted: "var(--th-muted)",
          heading: "var(--th-heading)",
          body: "var(--th-body)",
          label: "var(--th-label)",
          dim: "var(--th-dim)",
          ghost: "var(--th-ghost)",
          faint: "var(--th-faint)",
          line: "var(--th-line)",
          accent: "var(--th-accent)",
          "accent-s": "var(--th-accent-s)",
          "accent-l": "var(--th-accent-l)",
          danger: "var(--th-danger)",
          "danger-s": "var(--th-danger-s)",
          "danger-l": "var(--th-danger-l)",
          warn: "var(--th-warn)",
          "warn-s": "var(--th-warn-s)",
          "warn-l": "var(--th-warn-l)",
          ok: "var(--th-ok)",
          "ok-s": "var(--th-ok-s)",
          "ok-l": "var(--th-ok-l)",
          info: "var(--th-info)",
          "info-s": "var(--th-info-s)",
          "info-l": "var(--th-info-l)",
          sidebar: "var(--th-sidebar)",
          "sidebar-hover": "var(--th-sidebar-hover)",
          "sidebar-active": "var(--th-sidebar-active)",
          "sidebar-text": "var(--th-sidebar-text)",
          "sidebar-text-dim": "var(--th-sidebar-text-dim)",
        },
      },
      boxShadow: {
        "glow-sm": "0 0 4px -1px var(--th-accent)",
        glow: "0 0 8px -2px var(--th-accent)",
        "glow-lg": "0 0 16px -4px var(--th-accent)",
        card: "0 1px 2px 0 rgb(15 23 42 / 0.04), 0 4px 12px -3px rgb(15 23 42 / 0.08)",
        "card-hover": "0 2px 4px 0 rgb(15 23 42 / 0.05), 0 8px 20px -4px rgb(15 23 42 / 0.11)",
        "card-dark": "0 1px 4px -1px rgb(0 0 0 / 0.25)",
        "card-dark-hover": "0 2px 8px -2px rgb(0 0 0 / 0.3)",
        modal: "0 16px 24px -4px rgb(0 0 0 / 0.12), 0 6px 8px -4px rgb(0 0 0 / 0.1)",
        "modal-dark": "0 16px 32px -4px rgb(0 0 0 / 0.4)",
        "neon-accent": "0 0 8px -2px rgba(124, 132, 224, 0.2)",
        "neon-ok": "0 0 6px -2px rgba(92, 184, 122, 0.2)",
        "neon-warn": "0 0 6px -2px rgba(212, 168, 64, 0.2)",
        "neon-danger": "0 0 6px -2px rgba(217, 112, 112, 0.2)",
      },
      borderRadius: {
        xl: "0.75rem",
        "2xl": "1rem",
      },
      backdropBlur: {
        xs: "2px",
      },
      animation: {
        "fade-in": "fade-in 0.25s ease-out",
        "slide-up": "slide-up 0.25s ease-out",
        "slide-down": "slide-down 0.25s ease-out",
        "pulse-soft": "pulse-soft 2s ease-in-out infinite",
        "glow-pulse": "glow-pulse 2s ease-in-out infinite",
        "shimmer": "shimmer 2s linear infinite",
        "float": "float 3s ease-in-out infinite",
      },
      keyframes: {
        "fade-in": { "0%": { opacity: "0" }, "100%": { opacity: "1" } },
        "slide-up": { "0%": { opacity: "0", transform: "translateY(8px)" }, "100%": { opacity: "1", transform: "translateY(0)" } },
        "slide-down": { "0%": { opacity: "0", transform: "translateY(-8px)" }, "100%": { opacity: "1", transform: "translateY(0)" } },
        "pulse-soft": { "0%, 100%": { opacity: "1" }, "50%": { opacity: "0.7" } },
        "glow-pulse": { "0%, 100%": { boxShadow: "0 0 4px -1px currentColor" }, "50%": { boxShadow: "0 0 8px -2px currentColor" } },
        "shimmer": { "0%": { backgroundPosition: "-200% center" }, "100%": { backgroundPosition: "200% center" } },
        "float": { "0%, 100%": { transform: "translateY(0)" }, "50%": { transform: "translateY(-4px)" } },
      },
    },
  },
  plugins: [],
};
